name: Deploy to Fly.io

on:
  push:
    branches: [main]
  workflow_dispatch:

env:
  FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}

jobs:
  deploy:
    name: Deploy to Fly.io
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Fly CLI
        uses: superfly/flyctl-actions/setup-flyctl@master
        
      - name: Deploy to Fly
        run: |
          flyctl deploy --remote-only \
            --build-arg PCB_VERSION=${{ github.sha }}
            
      - name: Check deployment
        run: |
          flyctl status
          flyctl info